# Helm values overrides for MySQL Helm chart by Bitnami.
# Refer to https://github.com/bitnami/charts/blob/master/bitnami/mysql/values.yaml

auth:
  rootPassword: mysqlrootpass
  createDatabase: false
  username: lrvl_user
  password: mysqlpass
primary:
  persistence:
    enabled: true
    storageClass: ""
    accessModes:
    - ReadWriteOnce
    size: 8Gi
initdbScripts:
  db_init.sql:
