version: "3"

services:

  # Common containers
  database:
    image: mysql:8
    container_name: database_container
    #    ports:
    #      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysqlrootpass
#      MYSQL_DATABASE: lrvl_db_name
      MYSQL_USER: lrvl_user
      MYSQL_PASSWORD: mysqlpass
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/

  redis:
    container_name: redis_container
    image: redis:7-alpine3.16
    ports:
      - 6379:6379


  # Laravel Application containers
  lrvl-nginx:
    image: 078449232710.dkr.ecr.eu-west-1.amazonaws.com/lrvl-nginx:latest
    container_name: lrvl_nginx_container
    build:
        context: Laravel
        dockerfile: nginx.Dockerfile
    environment:
      PHP_UPSTREAM_CONTAINER: lrvl-php-fpm
      PHP_UPSTREAM_PORT: 9000
#    volumes:
#      - ./Laravel/src:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - lrvl-php-fpm

  lrvl-php-fpm:
    image: 078449232710.dkr.ecr.eu-west-1.amazonaws.com/lrvl-php-fpm:latest
    container_name: lrvl_php_fpm_container
    build:
        context: Laravel
        dockerfile: php-fpm.Dockerfile
    depends_on:
      - database
#    volumes:
#      - ./Laravel/src:/var/www/html


  lrvl-php-worker:
    image: 078449232710.dkr.ecr.eu-west-1.amazonaws.com/lrvl-php-cli:latest
    container_name: lrvl_php_worker_container
    build:
      context: Laravel
      dockerfile: php-cli.Dockerfile
    depends_on:
      - redis
      - database
#    volumes:
#      - ./Laravel/src:/var/www/html

  # Wordpress Application containers

  wordpress:
    image: 078449232710.dkr.ecr.eu-west-1.amazonaws.com/wordpress:latest
    build: ./Wordpress
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - ./Wordpress/src:/bitnami/wordpress
    depends_on:
      - database
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - WORDPRESS_DATABASE_HOST=database
      - WORDPRESS_DATABASE_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=root
      - WORDPRESS_DATABASE_NAME=wp
      - WORDPRESS_DATABASE_PASSWORD=mysqlrootpass


  nextjs:
    image: 078449232710.dkr.ecr.eu-west-1.amazonaws.com/nextjs:latest
    build:
        context: NextJs
        dockerfile: Dockerfile
    ports:
      - '3000:3000'
