apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "laravel.name" . }}-{{ .Values.php_fpm.name }}
  labels:
    {{- include "laravel.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.php_fpm.name }}
spec:
  replicas: {{ .Values.nginx.replicas }}
  selector:
    matchLabels:
      {{- include "laravel.labels" . | nindent 6 }}
      app.kubernetes.io/component: {{ .Values.php_fpm.name }}
  template:
    metadata:
      annotations:
        helmDate: {{ now | date "2006-01-02T15:04:05" }}
      labels:
        {{- include "laravel.labels" . | nindent 8 }}
        app.kubernetes.io/component: {{ .Values.php_fpm.name }}
    spec:
      serviceAccountName: {{ .Values.global.serviceAccount.name }}
      containers:
      - name: {{ .Values.php_fpm.name }}
        image: {{ .Values.php_fpm.image.repository }}:{{ .Values.php_fpm.image.tag | default "latest" }}
        imagePullPolicy: {{ .Values.php_fpm.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.php_fpm.service.targetPort }}
          protocol: TCP
        {{- with .Values.php_fpm.env }}
        env:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        resources:
          {{- toYaml .Values.php_fpm.resources | nindent 10 }}
        volumeMounts:
        - mountPath: /var/www/html/storage
          name: efs
      volumes:
      - name: efs
        persistentVolumeClaim:
          claimName: {{ include "laravel.name" . }}
      {{- with .Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
