apiVersion: v1
kind: Service
metadata:
  name: {{ include "laravel.name" . }}-{{ .Values.php_fpm.name }}
  labels:
    {{- include "laravel.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.php_fpm.name }}
spec:
  type: {{ .Values.php_fpm.service.type }}
  ports:
    - port: {{ .Values.php_fpm.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "laravel.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.php_fpm.name }}
