apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "laravel.name" . }}
  labels:
    {{- include "laravel.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: efs
