name: Remove EKS cluster

on:
  pull_request:
    types:
      - closed
    branches:
      - develop

env:
  AWS_DEFAULT_REGION: us-east-1
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}

jobs:
  # Build step
  destory:
    name: Delete app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.6.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Delete EKS namespace
        uses: docker://alpine/k8s:1.22.10
        with:
          entrypoint: /bin/bash
          args: kubectl delete namespace pr${{ github.event.number }} --all --force --wait

