name: Remove EKS cluster

on:
  pull_request:
    types:
      - closed
    branches:
      - develop

env:
  AWS_DEFAULT_REGION: eu-west-1
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}

jobs:
  # Build step
  destory:
    name: Delete app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.6.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: delete EKS namespace
        uses: koslib/helm-eks-action@v1.22.0
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
          IMAGE_TAG: ${{ github.sha }}
          PR_NUMBER: ${{ github.event.number }}
        with:
          plugins: "https://github.com/jkroepke/helm-secrets" # optional
          command: |
            kubectl delete namespace pr$PR_NUMBER --all --force --wait
